steps:
  - name: 'docker'
    args:
      - 'buildx'
      - 'create'
      - '--name'
      - 'mybuilder'
      - '--use'
  - name: 'docker'
    args: 
      - 'buildx'
      - 'build'
      - '--platform'
      - 'linux/amd64'
      - '-t'
      - 'us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/wi-demo:amd64-$SHORT_SHA'
      - '--load'
      - '.'
  - name: 'docker'
    args: 
      - 'buildx'
      - 'build'
      - '--platform'
      - 'linux/arm64'
      - '-t'
      - 'us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/wi-demo:arm64-$SHORT_SHA'
      - '--load'
      - '.'
  - name: 'docker'
    args: 
      - 'push'
      - 'us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/wi-demo:amd64-$SHORT_SHA'
  - name: 'docker'
    args: 
      - 'push'
      - 'us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/wi-demo:arm64-$SHORT_SHA'
  - name: 'docker'
    args: 
      - 'manifest'
      - 'create'
      - 'us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/wi-demo:$SHORT_SHA'
      - 'us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/wi-demo:amd64-$SHORT_SHA'
      - 'us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/wi-demo:arm64-$SHORT_SHA'
  - name: 'docker'
    args: 
      - 'manifest'
      - 'push'
      - 'us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/wi-demo:$SHORT_SHA'
images:
  - us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/wi-demo:amd64-$SHORT_SHA
  - us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/wi-demo:arm64-$SHORT_SHA
options:
  requestedVerifyOption: 'VERIFIED'
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REPO_NAME: gke-demos
